#FROM --platform=linux/amd64 node:22-alpine as build
FROM node:22-alpine as build

WORKDIR /app
COPY vue_test/ .

RUN npm install -g @vue/cli && npm install
RUN npm run build

#FROM --platform=linux/amd64 nginx:alpine as prod
FROM nginx:alpine as prod

WORKDIR /etc/nginx/conf.d

RUN mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.origin
COPY nginx_default.conf default.conf

WORKDIR /var/www/html
COPY --from=build /app/dist .

EXPOSE 9999

CMD [ "nginx", "-g", "daemon off;" ]



